buildscript {
    ext.kotlin_version = "2.0.0"
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.10.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()

        maven { url 'https://jitpack.io' }
        maven {
            url "https://plugins.gradle.org/m2/"
        }
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/plussaw/GluedIn")
            credentials {
                username = "plussaw"
                password = "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"
            }
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
